# -*- coding: utf-8 -*-
"""Task1b.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Al-j8twDB6TxX_R8pIicqu5hEVFUbI5Y
"""

#Task1B BFS Approach kahns
input = open("/content/drive/MyDrive/CSE221_LAB/LAB5/input1b.txt","r")
output = open("/content/drive/MyDrive/CSE221_LAB/LAB5/output1b.txt","w")

n = input.readline().split(" ")
nodes = int(n[0])+1
edges = int(n[1])

def topologicalSort(graph, nodes):

        indegree = [0]*nodes
        for i in range(nodes):
            for j in graph[i]:
                indegree[j] += 1

        q = []
        for i in range(1,nodes):
             if indegree[i] == 0:
                 q.append(i)

        topo_sort = []
        while q:
             node = q.pop()
             topo_sort.append(node)

             for i in graph[node]:
                  indegree[i] -= 1
                  if indegree[i] == 0:
                       q.append(i)

        if len(topo_sort) != nodes-1:
               output.write(f"Impossible")
        else:
               for i in range(len(topo_sort)):
                    output.write(f"{topo_sort[i]} ")

Graph = [[] for i in range(nodes)]
for i in range(edges):

    var = list(input.readline().split(" "))
    Graph[int(var[0])].append(int(var[1]))

topologicalSort(Graph, nodes)

input.close()
output.close()