# -*- coding: utf-8 -*-
"""Task1a.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Al-j8twDB6TxX_R8pIicqu5hEVFUbI5Y
"""

#Task1A DFS Approach
input = open("/content/drive/MyDrive/CSE221_LAB/LAB5/input1a.txt","r")
output = open("/content/drive/MyDrive/CSE221_LAB/LAB5/output1a.txt","w")

n = input.readline().split(" ")
nodes = int(n[0])+1
edges = int(n[1])

def DFS(nodes, graph, color, stack):

      color[nodes] = 1

      for i in graph[nodes]:
           if color[i] == 0:
              DFS(i, graph, color, stack)

           elif color[i] == 1:
                return stack

      color[nodes] = 2
      stack.append(nodes)

def topologicalSort(graph, nodes):

     stack = []
     color = [0]*(nodes)

     for i in range(1,nodes):
           if color[i] == 0:
              DFS(i, graph, color, stack)

     if len(stack) != nodes-1:
            output.write(f"Impossible")

     else:
         while stack:
            output.write(f"{stack.pop()} ")

Graph = [[] for i in range(nodes)]

for i in range(edges):

    var = list(input.readline().split(" "))
    Graph[int(var[0])].append(int(var[1]))

topologicalSort(Graph, nodes)

input.close()
output.close()