# -*- coding: utf-8 -*-
"""Task2.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Al-j8twDB6TxX_R8pIicqu5hEVFUbI5Y
"""

#TASK2 Lexicographical Sequence using BFS

import heapq as queue
input = open("/content/drive/MyDrive/CSE221_LAB/LAB5/input2.txt","r")
output = open("/content/drive/MyDrive/CSE221_LAB/LAB5/output2.txt","w")

n = input.readline().split(" ")
nodes = int(n[0])+1
edges = int(n[1])

Graph = [[] for i in range(nodes)]
for i in range(edges):

    var = list(input.readline().split(" "))
    Graph[int(var[0])].append(int(var[1]))

def topologicalSort(graph, nodes):

    in_degree = [0] * nodes

    for u in range(nodes):
        for x in graph[u]:
            in_degree[x] += 1

    s = []
    for i in range(1,nodes):
        if in_degree[i] == 0:
            queue.heappush(s, i)

    topo_sort = []

    while s:

        u = queue.heappop(s)
        topo_sort.append(u)
        for x in graph[u]:
            in_degree[x] -= 1
            if in_degree[x] == 0:
                queue.heappush(s, x)

    if len(topo_sort) != nodes-1:
        output.write(f"Impossible")

    else:
        for i in range(len(topo_sort)):
            output.write(f"{topo_sort[i]} ")

topologicalSort(Graph, nodes)
input.close()
output.close()