# -*- coding: utf-8 -*-
"""Task4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15JX6j4JjIMFXKfftR0SmBxO4H9T8tBbc
"""

from google.colab import drive
drive.mount('/content/drive')

#Task4
input = open("/content/drive/MyDrive/CSE221_LAB/Lab2/input4.txt","r")
output = open("/content/drive/MyDrive/CSE221_LAB/Lab2/output4.txt","w")

given = (input.readline()).split(" ")

n = int(given[0])
m = int(given[1])

schedule = []

for i in range(n):
      var = input.readline().split(" ")
      schedule.append(var)

def bubble_sort(arr):

      for i in range(len(arr)-1):

          for j in range(i+1,len(arr)):

              if arr[i][1] > arr[j][1] :
                    arr[i], arr[j] = arr[j], arr[i]

      return arr

def divide_task(arr,m):

     arr = bubble_sort(arr)
     worker = [None]*m
     total_work = []

     for i in range(len(arr)):

          min = -1
          for j in range(m):

              if worker[j] != None:
                  if int(arr[i][0]) >= int(worker[j]):
                           min = j

              else:
                   if min == -1:
                       min = j
                       break

          if min != -1:
                 worker[min] = int(arr[i][1])
                 total_work.append(arr[i])

     output.write(f"{len(total_work)}")

divide_task(schedule,m)
input.close()
output.close()