# -*- coding: utf-8 -*-
"""Task3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15JX6j4JjIMFXKfftR0SmBxO4H9T8tBbc
"""

from google.colab import drive
drive.mount('/content/drive')

#Task3
input = open("/content/drive/MyDrive/CSE221_LAB/Lab2/input3.txt","r")
output = open("/content/drive/MyDrive/CSE221_LAB/Lab2/output3.txt","w")

n = int(input.readline())
schedule = []

for i in range(n):
      var = input.readline().split(" ")
      schedule.append(var)

def bubble_sort(arr):

      for i in range(len(arr)-1):
          for j in range(i+1,len(arr)):
              if int(arr[i][1]) > int(arr[j][1]):
                  arr[i], arr[j] = arr[j], arr[i]
      return arr

def complete_task(arr):

     arr = bubble_sort(arr)
     last = 0
     total_task = 0
     s = ""
     for i in range(len(arr)):

           if int(arr[i][0]) >=  last:
                 last = int(arr[i][1])
                 total_task += 1
                 s += (f"{arr[i][0]} {arr[i][1]}")

     output.write(f"{total_task}\n")
     output.write(f"{s}")

complete_task(schedule)
input.close()
output.close()