# -*- coding: utf-8 -*-
"""Task1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15JX6j4JjIMFXKfftR0SmBxO4H9T8tBbc
"""

from google.colab import drive
drive.mount('/content/drive')

#Task1a
input = open("/content/drive/MyDrive/CSE221_LAB/Lab2/input1a.txt","r")
output = open("/content/drive/MyDrive/CSE221_LAB/Lab2/output1a.txt","w")

n = input.readline().split(" ")
arr = input.readline().split(" ")

def target_sum(arr,target): #0(n^2)

     idx2 = 0
     for i in range(len(arr)-1):
          sum = int(arr[i])
          idx1 = i+1
          for j in range(i+1,len(arr)):
              if sum + int(arr[j]) == target:
                   idx2 = j+1
                   break

          if idx2 != 0:
                 break

     if idx2 == 0:
          output.write(f"Impossible")
          return
     output.write(f"{idx1} {idx2}")
     return

target_sum(arr, int(n[1]))

input.close()
output.close()

#Task1b
input = open("/content/drive/MyDrive/CSE221_LAB/Lab2/input1b.txt","r")
output = open("/content/drive/MyDrive/CSE221_LAB/Lab2/output1b.txt","w")

n = input.readline().split(" ")
arr = input.readline().split(" ")

def target_sum_n(arr,target): #0(n)

      i = 0
      j = len(arr)-1

      while i < j:

           sum = int(arr[i])+int(arr[j])
           if sum > target:
                j = j-1
           elif sum < target:
                i = i+1
           elif sum == target:
                output.write(f"{i+1} {j+1}")
                return

      output.write(f"Impossible")
      return

target_sum_n(arr,int(n[1]))
input.close()
output.close()