# -*- coding: utf-8 -*-
"""Task2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15JX6j4JjIMFXKfftR0SmBxO4H9T8tBbc
"""

from google.colab import drive
drive.mount('/content/drive')

#Task2a
input = open("/content/drive/MyDrive/CSE221_LAB/Lab2/input2a.txt","r")
output = open("/content/drive/MyDrive/CSE221_LAB/Lab2/output2a.txt","w")

n = int(input.readline())
arr1 = input.readline().split(" ")
n2 = int(input.readline())
arr2 = input.readline().split(" ")

def merge_sort(arr): #0(nlogn)

      if len(arr) == 1:
            return

      if len(arr) > 1:

            left_arr = arr[:len(arr)//2]
            right_arr = arr[len(arr)//2:]

            merge_sort(left_arr)
            merge_sort(right_arr)
            i = 0
            j = 0
            k = 0

            while i < len(left_arr) and j < len(right_arr):

                if int(left_arr[i]) < int(right_arr[j]):
                    arr[k] = int(left_arr[i])
                    i += 1

                else:
                    arr[k] = int(right_arr[j])
                    j += 1

                k += 1

            for i in range(i,len(left_arr)):
                    arr[k] = int(left_arr[i])
                    k += 1
            for j in range(j,len(right_arr)):
                    arr[k] = int(right_arr[j])
                    k += 1

            return arr

sorted_arr = merge_sort(arr1+arr2)
output.write(f"{sorted_arr}")
input.close()
output.close()

#Task2b
input = open("/content/drive/MyDrive/CSE221_LAB/Lab2/input2b.txt","r")
output = open("/content/drive/MyDrive/CSE221_LAB/Lab2/output2b.txt","w")

n = int(input.readline())
arr1 = input.readline().split(" ")
n2 = int(input.readline())
arr2 = input.readline().split(" ")

def Merge_sort(left_arr,right_arr): #0(n)

            i = 0
            j = 0
            k = 0
            arr = [None]*(len(left_arr)+len(right_arr))

            while i < len(left_arr) and j < len(right_arr):

                if int(left_arr[i]) < int(right_arr[j]):
                    arr[k] = int(left_arr[i])
                    i += 1

                else:
                    arr[k] = int(right_arr[j])
                    j += 1

                k += 1

            for i in range(i,len(left_arr)):
                    arr[k] = int(left_arr[i])
                    k += 1
            for j in range(j,len(right_arr)):
                    arr[k] = int(right_arr[j])
                    k += 1

            return arr

sorted_arr = Merge_sort(arr1,arr2)
output.write(f"{sorted_arr}")
input.close()
output.close()