# -*- coding: utf-8 -*-
"""Task5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pe82Kgtn2MFFiBXngzADW65LhyrfxrSV
"""

from google.colab import drive
drive.mount('/content/drive')

# Task5
input = open("/content/drive/MyDrive/CSE221_LAB/LAB3/input5.txt","r")
output = open("/content/drive/MyDrive/CSE221_LAB/LAB3/output5.txt","w")

n = int(input.readline())
arr = input.readline().split(" ")
for i in range(n):
     arr[i] = int(arr[i])

def partition(array, left, right):

	pivot = array[right]
	i = left - 1

	for j in range(left, right):
		if array[j] <= pivot:

			i = i + 1

			(array[i], array[j]) = (array[j], array[i])

	(array[i + 1], array[right]) = (array[right], array[i + 1])
	return i + 1


def quicksort(array, left, right):

	if left < right:

		j = partition(array, left, right)
		quicksort(array, left, j - 1)
		quicksort(array, j + 1, right)

quicksort(arr,0,n-1)
output.write(f"{arr}")
input.close()
output.close()