# -*- coding: utf-8 -*-
"""Task3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pe82Kgtn2MFFiBXngzADW65LhyrfxrSV
"""

from google.colab import drive
drive.mount('/content/drive')

#Task3
input = open("/content/drive/MyDrive/CSE221_LAB/LAB3/input3.txt","r")
output = open("/content/drive/MyDrive/CSE221_LAB/LAB3/output3.txt","w")

n = int(input.readline())
arr = input.readline().split(" ")

count = 0
def count_inversion(arr): #0(nlogn)

       if len(arr) == 1:
             return arr

       if len(arr) > 1:

            mid = len(arr)//2
            left = count_inversion(arr[:mid])
            right = count_inversion(arr[mid:])
            return merge(left,right)

def merge(left,right): #0(nlogn)

        i = j = 0
        new_arr = []
        global count

        while i < len(left) and j < len(right):

            if int(left[i]) > int(right[j]):
                new_arr.append(left[i])
                count += len(right)-j
                i += 1

            else:
                new_arr.append(right[j])
                j += 1

        new_arr.extend(left[i:])
        new_arr.extend(right[j:])

        return new_arr

arr = count_inversion(arr)
output.write(f"{count}")
input.close()
output.close()