# -*- coding: utf-8 -*-
"""Task1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pe82Kgtn2MFFiBXngzADW65LhyrfxrSV
"""

from google.colab import drive
drive.mount('/content/drive')

#Task1
input = open("/content/drive/MyDrive/CSE221_LAB/LAB3/input1.txt","r")
output = open("/content/drive/MyDrive/CSE221_LAB/LAB3/output1.txt","w")

n = int(input.readline())
arr1 = input.readline().split(" ")

def merge_sort(arr): #0(nlogn)

       if len(arr) == 1:
             return arr

       if len(arr) > 1:

            mid = len(arr)//2
            left = merge_sort(arr[:mid])
            right = merge_sort(arr[mid:])
            return merge(left,right)

def merge(left,right): #0(nlogn)

        i = j = 0
        new_arr = []

        while i < len(left) and j < len(right):

            if int(left[i]) < int(right[j]):
                new_arr.append(left[i])
                i += 1

            else:
                new_arr.append(right[j])
                j += 1

        new_arr.extend(left[i:])
        new_arr.extend(right[j:])

        return new_arr

sorted_arr = merge_sort(arr1)
for i in range(len(sorted_arr)):
      output.write(f"{sorted_arr[i]} ")

input.close()
output.close()