# -*- coding: utf-8 -*-
"""Task6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pe82Kgtn2MFFiBXngzADW65LhyrfxrSV
"""

from google.colab import drive
drive.mount('/content/drive')

##TASK 6
input_text=open('/content/drive/MyDrive/CSE221_LAB/LAB3/input6.txt','r')
output_text=open('/content/drive/MyDrive/CSE221_LAB/LAB3/output6.txt','w')

size = int(input_text.readline())
arr=input_text.readline().split()

for i in range(len(arr)):
    arr[i]=int(arr[i])

task=int(input_text.readline())


def partition(arr,p,q):

    pivot = arr[p]
    i = p
    for j in range(p+1,q):

        if arr[j] <= pivot:
            i=i+1
            arr[i],arr[j] = arr[j],arr[i]

    arr[p],arr[i] = arr[i],arr[p]
    return i


def kth_element(arr,left,right,k):

    if left<right:

        q = partition(arr,left,right)

        if q == k-1:
            return arr[q]

        elif q < k-1:
            return kth_element(arr,q+1,right,k)


        elif q > k-1:
            return kth_element(arr,left,q,k)


for i in range(task):

    k=int(input_text.readline())
    key = kth_element(arr,0,len(arr),k)
    output_text.write(str(key) + '\n')
input_text.close()
output_text.close()