# -*- coding: utf-8 -*-
"""Task4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pe82Kgtn2MFFiBXngzADW65LhyrfxrSV
"""

from google.colab import drive
drive.mount('/content/drive')

#Task4
input = open("/content/drive/MyDrive/CSE221_LAB/LAB3/input4.txt","r")
output = open("/content/drive/MyDrive/CSE221_LAB/LAB3/output4.txt","w")

max_square = -9999999999
def maximum_value(arr): #0(nlogn)

       if len(arr) == 1:
             return arr

       if len(arr) > 1:

            mid = len(arr)//2
            left = maximum_value(arr[:mid])
            right = maximum_value(arr[mid:])
            maxi = maximum_square(left,right)
            return maxi

def maximum_square(left,right): #0(nlogn)

        temp = []
        temp += left+right
        global max_square
        left_max = max(left)
        new_max = -9999999999
        for j in range(len(right)):
            max1 = left_max + (abs(right[j]))**2
            if max1 > new_max:
                  new_max = max1

        if new_max > max_square:
              max_square = new_max

        return temp

n = int(input.readline())
arr = input.readline().split(" ")

for i in range(n):
     arr[i] = int(arr[i])

new = maximum_value(arr)
output.write(f"{max_square}")

input.close()
output.close()