# -*- coding: utf-8 -*-
"""Task2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pe82Kgtn2MFFiBXngzADW65LhyrfxrSV
"""

from google.colab import drive
drive.mount('/content/drive')

#Task2
input = open("/content/drive/MyDrive/CSE221_LAB/LAB3/input2.txt","r")
output = open("/content/drive/MyDrive/CSE221_LAB/LAB3/output2.txt","w")

n = int(input.readline())
arr = input.readline().split(" ")

def maximum(n1,n2):

      if n1 > n2:
           return n1
      return n2

def find_max(arr,l = 0,h = 0):

      if l == h:
            return int(arr[l])

      mid = (l+h)//2
      left = find_max(arr,l,mid)
      right = find_max(arr,mid+1,h)

      return maximum(left,right)

maxi = find_max(arr,0,n-1)
output.write(f"{maxi}")

input.close()
output.close()