# -*- coding: utf-8 -*-
"""22241022_Group5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-EFCPq8FSZ28yOVSk9ZSO34k8NmbdhFK
"""

from google.colab import drive
drive.mount('/content/drive')

input = open("/content/drive/MyDrive/Lab Evaluation/input1.txt","r")
output = open("/content/drive/MyDrive/Lab Evaluation/output1.txt","w")

n = int(input.readline())
tree = input.readline().split(" ")

for i in range(len(tree)):
         tree[i] = int(tree[i])

def maximum_water(height):

    maximum_area = 0
    for i in range(len(height)-1):
        for j in range(i + 1, len(height)):
            height = min(height[i], height[j])
            width = j - i
            new_area = height * width
            if new_area > maximum_area:
                  maximum_area = new_area

    output.write(f"{maximum_area }")

maximum_water(tree)
print(tree)
input.close()
output.close()

