# -*- coding: utf-8 -*-
"""Task2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oms8g-37hCECxADrVg8p5zhsOWw_fSKL
"""

from google.colab import drive
drive.mount('/content/drive')

#2
import math

input = open("/content/drive/MyDrive/CSE221_LAB/LAB6/input2.txt", "r")
output = open("/content/drive/MyDrive/CSE221_LAB/LAB6/output2.txt", "w")

nodes,edges  = map(int, input.readline().split(' '))
list_1 = input.readlines()
graph={}

for y in list_1:
    x = list(map(int,y.split(' ') ))
    if len(x) ==2:
        s1,s2 = x[0],x[1]
    else:
        u,v,w=x[0],x[1],x[2]
        if u in graph.keys():
            graph[u].append((v,w))
        else:
            graph[u] = [(v,w)]

def dequeue(queue, distance, flag,path):
    minimum = math.inf
    for i in range(len(queue)):
        if distance[queue[i]] < minimum:
            idx = i
            minimum = distance[queue[idx]]
    u = queue.pop(idx)
    flag[u] = True
    if u not in path:
        path.append(u)
    return u

def dijkstra(graph,s,n):
    distance = [math.inf] * (n+1)
    distance[s] = 0
    queue = [s]
    path =[s]
    flag = [False] * (n+1)
    flag[s] = True

    while queue:
        u = dequeue(queue, distance, flag, path)
        if u in graph.keys():
            for x in graph[u]:
                v, w = x[0] , x[1]
                if flag[v] == False:
                    queue.append(v)
                    temp = distance[u] + w
                    if temp < distance[v]:
                        distance[v] = temp

        if False not in flag:
            break
    return (distance,path)

a = dijkstra(graph,s1,nodes)
d1, p1 = a[0], a[1]
b = dijkstra(graph,s2,nodes)
d2, p2 = b[0], b[1]
i,j=0,0


while True:
    if p1[i] == p2[j]:
        temp = p1[i]
        output.write('Time '+str(max(d1[temp],d2[temp]))+'\n')
        output.write('Node '+str(temp))
        break
    if i == len(p1)-1 and j == len(p2)-1:
        output.write('IMPOSSIBLE')
        break
    if i!=len(p1)-1:
        i+=1
    if j!=len(p2)-1:
        j+=1
input.close()
output.close()