# -*- coding: utf-8 -*-
"""Task1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oms8g-37hCECxADrVg8p5zhsOWw_fSKL
"""

from google.colab import drive
drive.mount('/content/drive')

#1
import math

input = open("/content/drive/MyDrive/CSE221_LAB/LAB6/input1.txt", "r")
output = open("/content/drive/MyDrive/CSE221_LAB/LAB6/output1.txt", "w")
nodes,edges  = map(int, input.readline().split(' '))
list_1 = input.readlines()
graph={}

for x in list_1:
    if len(x) == 1:
        s = int(x)
    else:
        u,v,w=map(int, x.split(' '))
        if u in graph.keys():
            graph[u].append((v,w))
        else:
            graph[u] = [(v,w)]

def dequeue(queue, distance, flag):

        min = math.inf
        for i in range(len(queue)):
            if distance[queue[i]] <min:
                idx = i
                min = distance[queue[idx]]
        u = queue.pop(idx)
        flag[u] = True
        return u

def dijkstra(graph,s,n):

            distance = [math.inf] * (n+1)
            distance[s] = 0
            queue = [s]
            flag = [False] * (n+1)
            flag[s] = True
            while queue:
                u = dequeue(queue, distance, flag)
                if u in graph.keys():
                    for x in graph[u]:
                        v, w = x[0] , x[1]
                        if flag[v] == False:
                            queue.append(v)
                            temp = distance[u] + w
                            if temp < distance[v]:
                                distance[v] = temp
                if False not in flag:
                    break
            distance = distance[1:]
            for i in range(len(distance)):
                if distance[i] == math.inf:
                    distance[i] = -1
                output.write(str(distance[i]) + ' ')
            return

dijkstra(graph,s,nodes)

input.close()
output.close()