# -*- coding: utf-8 -*-
"""Task3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oms8g-37hCECxADrVg8p5zhsOWw_fSKL
"""

from google.colab import drive
drive.mount('/content/drive')

#3
import math

input = open("/content/drive/MyDrive/CSE221_LAB/LAB6/input3.txt", "r")
output = open("/content/drive/MyDrive/CSE221_LAB/LAB6/output3.txt", "w")

n,e  = map(int, input.readline().split(' '))
list_1 = input.readlines()
graph={}

for x in list_1:
    if len(x) == 1:
        s = int(x)
    else:
        u,v,w=map(int, x.split(' '))
        if u in graph.keys():
            graph[u].append((v,w))
        else:
            graph[u] = [(v,w)]


distance = [math.inf] * (n+1)
distance[1] = 0
flag = [False] * (n+1)
flag[0] = True


for k in range(n):
    minimum = math.inf
    minimum_node = None

    for j in range(1,n+1):
        if flag[j] == False and distance[j] < minimum:
            minimum = distance[j]
            minimum_node = j
    if minimum_node == None:
        if any(flag) == True:
            output.write('IMPOSSIBLE')
        break
    if minimum_node == n :
        output.write(str(minimum))
        break
    flag[minimum_node] = True
    if minimum_node in graph.keys():
        for x in graph[minimum_node]:
            v,w = x[0], x[1]
            d = max(minimum, w)
            if d<distance[v]:
                distance[v] = d
if minimum_node != n:
    if False in flag:
        output.write('IMPOSSIBLE')
input.close()
output.close()