# -*- coding: utf-8 -*-
"""Task3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xK6W3_4yI1twbCwn1FnqK72WWVJTjSm3
"""



#Task3
input = open("/content/drive/MyDrive/CSE221_LAB/LAB1/input3.txt","r")
output = open("/content/drive/MyDrive/CSE221_LAB/LAB1/output3.txt","w")

n=int(input.readline())
marks = input.readline().split()
id = input.readline().split()

def selection_sort(student_id,obtained_marks):

      for i in range(len(student_id)):

           marks_index = i
           for j in range(i+1,len(student_id)):

                  if int(obtained_marks[j]) > int(obtained_marks[marks_index]):
                      marks_index = j

                  if int(obtained_marks[marks_index]) == int(obtained_marks[j]):
                        if int(student_id[marks_index]) > int(student_id[j]):
                               marks_index = j

           obtained_marks[i],obtained_marks[marks_index] = obtained_marks[marks_index],obtained_marks[i]
           student_id[i], student_id[marks_index] = student_id[marks_index], student_id[i]

      return obtained_marks, student_id

def result(id,marks):

       marks,id = selection_sort(marks,id)

       for i in range(len(marks)):
          output.write(f"ID: {id[i]} Mark: {marks[i]} \n")

result(id,marks)
input.close()
output.close()