# -*- coding: utf-8 -*-
"""Task4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xK6W3_4yI1twbCwn1FnqK72WWVJTjSm3
"""

#Task4
input = open("/content/drive/MyDrive/CSE221_LAB/LAB1/input4.txt","r")
output = open("/content/drive/MyDrive/CSE221_LAB/LAB1/output4.txt","w")

n = int(input.readline())

name = []
destination = []
arrival=[]

for i in range(n) :

    var = input.readline().split()
    name.append(var[0])
    destination.append(var[4])
    arrival.append(var[6])

def train_departure(name,arrival,destination,n):

    for i in range(n-1):
        idx = i
        for j in range(i+1,n):

            if name[idx] > name[j]:
                    idx = j

            elif name[idx] == name[j]:

                if int(arrival[idx][0:2])>int(arrival[j][0:2]):

                        destination [idx],destination[j]=destination[j],destination[idx]
                        arrival[idx],arrival[j] = arrival[j],arrival[idx]
                        idx = j

                elif int(arrival[idx][0:2]) == int(arrival[j][0:2]):
                    if int(arrival[idx][4::])>int(arrival[j][4::]):
                        arrival[idx],arrival[j]=arrival[j],arrival[idx]
                        destination[idx],destination[j] = destination[j],destination[idx]
                        idx = j

        destination[i],destination[idx] = destination[idx],destination[i]
        arrival[i],arrival[idx] = arrival[idx],arrival[i]
        name[i],name[idx] = name[idx],name[i]

    for i in range(n):
           output.write(f"{name[i]} will departure for {destination[i]} at {arrival[i]}\n")

train_departure(name,arrival,destination,n)
input.close()
output.close()