# -*- coding: utf-8 -*-
"""Task1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xK6W3_4yI1twbCwn1FnqK72WWVJTjSm3
"""

#Task1a
input = open("/content/drive/MyDrive/CSE221_LAB/LAB1/input1a.txt","r")
output = open("/content/drive/MyDrive/CSE221_LAB/LAB1/output1a.txt","w")

n = int(input.readline())

for i in range(n):

     var = int(input.readline())
     if var%2 == 0:
          output.write(f"{var} is an Even number \n")
     else:
          output.write(f"{var} is an Odd number \n")

input.close()
output.close()

#Task1b
input = open("/content/drive/MyDrive/CSE221_LAB/LAB1/input1b.txt",'r')
output = open("/content/drive/MyDrive/CSE221_LAB/LAB1/output1b.txt",'w')

n = int(input.readline())

for i in range(n):

          var = input.readline().split()
          if var[2] == "+":
              result = int(var[1]) + int(var[3])
          elif var[2] == "-":
              result = int(var[1]) - int(var[3])
          elif var[2] == "/":
              result = int(var[1]) / int(var[3])
          elif var[2] == "*":
              result = int(var[1]) * int(var[3])
          line = var[1]+var[2]+var[3]
          output.write(f"The result of {line} is {result}\n")

input.close()
output.close()