# -*- coding: utf-8 -*-
"""Task2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xK6W3_4yI1twbCwn1FnqK72WWVJTjSm3
"""

#Task2
input = open("/content/drive/MyDrive/CSE221_LAB/LAB1/input2.txt",'r')
output = open("/content/drive/MyDrive/CSE221_LAB/LAB1/output2.txt",'w')

n=int(input.readline())
arr = input.readline().split()

for i in range(len(arr)-1):

    flag = False

    for j in range(len(arr)-i-1):

        if int(arr[j]) > int(arr[j+1]):
            arr[j], arr[j+1] = arr[j+1], arr[j]
            flag = True

    if flag == False:
        break

for i in range(len(arr)):
    output.write(f"{arr[i]} ")

input.close()
output.close()

"""Here, I used the flag variable just to check that if the array is already sorted, then there will be no unnecessary iteration and if the loop runs for the first time and the flag variable is not updated then it will break the loop and will achieve a time complexity of 0(n) for the best case scenario."""