# -*- coding: utf-8 -*-
"""Task4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UinA4W_Jm2y6kYTVGB65boaaifLnxSL6
"""

from google.colab import drive
drive.mount('/content/drive')

#Task4
input_file = open('/content/drive/MyDrive/CSE221_LAB/LAB4/input4.txt', 'r')
output_file = open('/content/drive/MyDrive/CSE221_LAB/LAB4/output4.txt', 'w')

n = input_file.readline().split(" ")
nodes = int(n[0]) + 1
edges = int(n[1])

def array_graph(nodes, edges):
    adj_arr = [[] for _ in range(nodes)]

    for _ in range(edges):
        var = input_file.readline().split(" ")
        source = int(var[0])
        destination = int(var[1])
        adj_arr[source].append(destination)

    return adj_arr

adj_array = array_graph(nodes, edges)

def has_cycle(node, color, adj_arr):

    color[node] = 1

    for neighbor in adj_arr[node]:
        if color[neighbor] == 0:
            if has_cycle(neighbor, color, adj_arr):
                return True

        elif color[neighbor] == 1:
            return True

    color[node] = 2
    return False

def cycle_detection(adj_arr):
    color = [0] * nodes

    for vertex in range(nodes):
        if color[vertex] == 0:
            if has_cycle(vertex, color, adj_arr):
                return 'Yes'

    return 'No'

result = cycle_detection(adj_array)
output_file.write(result)

input_file.close()
output_file.close()

