# -*- coding: utf-8 -*-
"""Task5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UinA4W_Jm2y6kYTVGB65boaaifLnxSL6
"""

from google.colab import drive
drive.mount('/content/drive')

#Task5
input_file = open('/content/drive/MyDrive/CSE221_LAB/LAB4/input5.txt', 'r')
output_file = open('/content/drive/MyDrive/CSE221_LAB/LAB4/output5.txt', 'w')

n = input_file.readline().split(" ")
nodes = int(n[0])
edges = int(n[1])
end = int(n[2])
Graph_set = {}

for i in range(edges):
    n = input_file.readline().split()
    node = int(n[0])
    edge = int(n[1])

    if node in Graph_set:
        Graph_set[node].append(edge)
    else:
        Graph_set[node] = [edge]

    if edge in Graph_set:
        Graph_set[edge].append(node)
    else:
        Graph_set[edge] = [node]

def shortest_path(adj_list, start, target):

    queue = [start]
    color = [0] * (len(adj_list) + 1)
    path = [0] * (len(adj_list) + 1)

    color[start] = 1
    path[start] = start

    while queue:
        u = queue.pop(0)

        for v in adj_list[u]:
            if color[v] == 0:
                color[v] = 1
                path[v] = u
                queue.append(v)
            if v == target:
                break

    result = []
    while True:
        result.append(target)
        if target == start:
            break
        target = path[target]
    result.reverse()

    output_file.write(f"Time : {len(result)-1}\n")
    output_file.write("Shortest Path: " + " ".join(map(str, result)))

shortest_path(Graph_set, 1, end)

input_file.close()
output_file.close()

