# -*- coding: utf-8 -*-
"""Task6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UinA4W_Jm2y6kYTVGB65boaaifLnxSL6
"""

from google.colab import drive
drive.mount('/content/drive')

#TASK6
import numpy as np
input = open('/content/drive/MyDrive/CSE221_LAB/LAB4/input6.txt', 'r')
output = open('/content/drive/MyDrive/CSE221_LAB/LAB4/output6.txt', 'w')

nodes , edge = input.readline().split(' ')
nodes = int(nodes)
edge = int(edge)

row = nodes+1
col = edge+1
arr=np.zeros((row,col),str)

for i in range(edge):
    n=input.readline().strip()
    for j in range(len(n)):
        arr[i][j] = n[j]

color=[]

for i in range(row):
    color.append([False])
    for j in range(col-1):
        color[i].append(False)

def collect_diamonds(arr,color,r,c):

    if r < 0 or r >= len(arr) or c < 0 or c >= len(arr[0]) or color[r][c] or arr[r][c] == '#':
        return 0

    color[r][c]=True
    count=0

    if arr[r][c]=="D":
        count+=1
    count += collect_diamonds(arr,color,r+1,c)
    count += collect_diamonds(arr,color,r,c+1)
    count += collect_diamonds(arr,color,r-1,c)
    count += collect_diamonds(arr,color,r,c-1)

    return count

max=0

for i in range(row):
    for j in range(col):
        if arr[i][j]=='.':
            count = collect_diamonds(arr,color,i, j)
            if count>max:
                max=count

output.write(f"{max}")

output.close()
input.close()

