# -*- coding: utf-8 -*-
"""Task3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UinA4W_Jm2y6kYTVGB65boaaifLnxSL6
"""

from google.colab import drive
drive.mount('/content/drive')

#Task3
input = open('/content/drive/MyDrive/CSE221_LAB/LAB4/input3.txt', 'r')
output = open('/content/drive/MyDrive/CSE221_LAB/LAB4/output3.txt', 'w')

n = input.readline().split(" ")
nodes = int(n[0])
edges = int(n[1])
Graph_set = {}
color = [0] * (nodes + 1)

for i in range(edges):
    n = input.readline().split()
    node = n[0]
    edge = n[1]
    node_opp = n[1]
    edge_opp = n[0]

    if node in Graph_set:
        Graph_set[node].append(edge)
    else:
        Graph_set[node] = [edge]
    if node_opp in Graph_set:
        Graph_set[node_opp].append(edge_opp)
    else:
        Graph_set[node_opp] = [edge_opp]


def DFS(graph, color, start):
    color[int(start)] = 1
    output.write(f"{start} ")
    for vertex in graph[start]:
        if color[int(vertex)] == 0:
            DFS(graph, color, vertex)

DFS(Graph_set, color, "1")

input.close()
output.close()

