# -*- coding: utf-8 -*-
"""Task1b

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UinA4W_Jm2y6kYTVGB65boaaifLnxSL6
"""

from google.colab import drive
drive.mount('/content/drive')

#Task1b
input = open("/content/drive/MyDrive/CSE221_LAB/LAB4/input1b.txt","r")
output = open("/content/drive/MyDrive/CSE221_LAB/LAB4/output1b.txt","w")

n = input.readline().split(" ")
nodes = int(n[0])+1
edges = int(n[1])

def array_graph(nodes,edges):

    adj_matrix = [[] for i in range(nodes)]
    for i in range(edges):

        var = list(input.readline().split(" "))
        adj_matrix[int(var[0])].append((int(var[1]),int(var[2])))
    return adj_matrix

adj_array = array_graph(nodes,edges)

for i in range(nodes):
           output.write(f"{i} : {adj_array[i]}\n")

input.close()
output.close()

