# -*- coding: utf-8 -*-
"""Task1a

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UinA4W_Jm2y6kYTVGB65boaaifLnxSL6
"""

from google.colab import drive
drive.mount('/content/drive')

#Task1a
input = open("/content/drive/MyDrive/CSE221_LAB/LAB4/input1a.txt","r")
output = open("/content/drive/MyDrive/CSE221_LAB/LAB4/output1a.txt","w")

n = input.readline().split(" ")
nodes = int(n[0])+1
edges = int(n[1])

def matrix_graph(nodes,edges):
        adj_matrix = [[0]*nodes for i in range(nodes)]
        for i in range(edges):
            var = input.readline().split(" ")
            adj_matrix[int(var[0])][int(var[1])] = int(var[2])
        return adj_matrix

adj_matrix = matrix_graph(nodes,edges)

for i in range(edges):
      for j in range(edges):
           output.write(f"{adj_matrix[i][j]} ")
      output.write(f"\n")

input.close()
output.close()

