# -*- coding: utf-8 -*-
"""Task2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UinA4W_Jm2y6kYTVGB65boaaifLnxSL6
"""

from google.colab import drive
drive.mount('/content/drive')

#Task2
input_file = open("/content/drive/MyDrive/CSE221_LAB/LAB4/input2.txt", "r")
output_file = open("/content/drive/MyDrive/CSE221_LAB/LAB4/output2.txt", "w")

n = input_file.readline().split(" ")
nodes = int(n[0])
edges = int(n[1])
Graph_set = {}
color = [0] * (nodes + 1)  # Initialize color list with zeros

for i in range(edges):
    n = input_file.readline().split()
    node = int(n[0])
    edge = int(n[1])

    if node in Graph_set:
        Graph_set[node].append(edge)
    else:
        Graph_set[node] = [edge]

    if edge in Graph_set:
        Graph_set[edge].append(node)
    else:
        Graph_set[edge] = [node]

def bfs(adj_list, colors, start):
    q = [start]
    colors[start] = 1

    while q:
        start = q.pop(0)
        output_file.write(f"{start} ")
        for vertex in adj_list.get(start, []):
            if colors[vertex] == 0:
                colors[vertex] = 1
                q.append(vertex)

bfs(Graph_set, color, 1)

input_file.close()
output_file.close()

