# -*- coding: utf-8 -*-
"""Task2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NV6zjTp8dIU-TAqBgeWhUlTTMHBDRFoi
"""

from google.colab import drive
drive.mount('/content/drive')

#Task2
input = open("/content/drive/MyDrive/CSE221_LAB/LAB7/input2.txt","r")
output = open("/content/drive/MyDrive/CSE221_LAB/LAB7/output2.txt","w")

a = input.readline().split()
n,m=int(a[0]),int(a[1])

edges=[]
for i in range(m):
  a = input.readline().split()
  a,b,w=int(a[0]),int(a[1]),int(a[2])
  edges.append((a,b,w))

def check(parent, i):
    if parent[i] == i:
        return i
    return check(parent, parent[i])

def mutual(parent, path, x, y):

    route1 = check(parent, x)
    route2 = check(parent, y)

    if path[route1] < path[route2]:
        parent[route1] = route2
    elif path[route1] > path[route2]:
        parent[route2] = route1
    else:
        parent[route2] = route1
        path[route1] += 1

def kruskal(edges, n):

    edges.sort(key=lambda x: x[2])
    parent = list(range(n+1))

    path = [0] * (n+1)
    minimum_cost = 0

    for vertex in edges:
        u, v, w = vertex

        if check(parent, u) != check(parent, v):
            mutual(parent, path, u, v)
            minimum_cost += w

    return minimum_cost



minimum_cost = kruskal(edges, n)

output.write(str(minimum_cost))
input.close()
output.close()