# -*- coding: utf-8 -*-
"""Task4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NV6zjTp8dIU-TAqBgeWhUlTTMHBDRFoi
"""

from google.colab import drive
drive.mount('/content/drive')

#task4

import math
input = open("/content/drive/MyDrive/CSE221_LAB/LAB7/input4.txt","r")
output = open("/content/drive/MyDrive/CSE221_LAB/LAB7/output4.txt","w")

x= input.readline().split()

n, target = int(x[0]),int(x[1])
x = input.readline().split()

for i in range(len(x)):

  x[i] = int(x[i])

def minimum_coin(n, target, coins):

    c = [math.inf] * (target + 1)
    c[0] = 0

    for i in range(1, target + 1):
        for coin in coins:
            if i - coin >= 0:
                c[i] = min(c[i], c[i - coin] + 1)

    if c[target] == math.inf:
        return -1
    else:
        return c[target]



result = minimum_coin(n,target,x)
output.write(str(result))
input.close()
output.close()