# -*- coding: utf-8 -*-
"""Task3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NV6zjTp8dIU-TAqBgeWhUlTTMHBDRFoi
"""

from google.colab import drive
drive.mount('/content/drive')

#Task3

input = open("/content/drive/MyDrive/CSE221_LAB/LAB7/input3.txt","r")
output = open("/content/drive/MyDrive/CSE221_LAB/LAB7/output3.txt","w")

n = input.readline()
n = int(n)

def total_jump(s):

    if s == 1:
        return 1
    elif s == 2:
        return 2

    stairs = [0] * (s + 1)

    stairs[1] = 1
    stairs[2] = 2

    for i in range(3, s + 1):
        stairs[i] = stairs[i - 1] + stairs[i - 2]

    return stairs[s]

freddy = total_jump(n)
output.write(f"{freddy}")

input.close()
output.close()