# -*- coding: utf-8 -*-
"""Task1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NV6zjTp8dIU-TAqBgeWhUlTTMHBDRFoi
"""

from google.colab import drive
drive.mount('/content/drive')

# task 1
input = open("/content/drive/MyDrive/CSE221_LAB/LAB7/input1.txt","r")
output = open("/content/drive/MyDrive/CSE221_LAB/LAB7/output1.txt","w")

x = input.readline().split()
n, k = int(x[0]),int(x[1])

def check(p, i):

    if p[i] == i:
        return i
    return check(p, p[i])

def mutual(friends, size, x, y):

    friend1 = check(friends, x)
    friend2 = check(friends, y)

    if friend1 != friend2:
        if size[friend1] < size[friend2]:
            friend1, friend2 = friend2, friend1
        friends[friend2] = friend1
        size[friend1] += size[friend2]

def friend_circle(n,k):

    friends = list(range(n))
    size = [1]*n

    for i in range(k):

        n = input.readline().split()
        f1, f2 = int(n[0]),int(n[1])
        mutual(friends, size, f1 - 1, f2 - 1)
        output.write(f"{str(size[check(friends, f1 - 1)])} \n")

friend_circle(n,k)
input.close()
output.close()